name: Main

on:
  pull_request:
  push: { branches: ["main"] }
  workflow_dispatch: # Can run manually from the Actions tab

permissions: {}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: git-lfs-hub/ci-cd/actions/init@main
        with: { peers: lib }

      - run: bun audit --audit-level=high

  can-merge:
    name: Can merge
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: git-lfs-hub/ci-cd/actions/check-can-merge@main
